Refactor iocla public repository
systems-cs-pub-ro/iocla pull request #1
Opened 2020-09-01 21:35 UTC by albisorua

Legat de structurare am vrea sa compactam repo-urile existente in unul singur public si sa avem o oarecare organizare (ex. [template](https://github.com/albisorua)).
As vrea feedback legat de chestii pe care le-ati vrea structurate in alt mod.
Totodata, la ce curs ar trebui sa intre directoarele `Linux_IOFiles, link-load si misc`?
Iar la [link](https://github.com/iocla) vad ca sunt mai multe repo-uri si as vrea sa stiu daca le facem merge tuturor si eventual mai adaugam in structura un folder pentru fiecare curs (ex. extra-stuff-CA). Momentan e merge-uit doar cel de [demo-uri](https://github.com/iocla/demo).

Andrei Albisoru: andreialbisoru98@gmail.com

2020-09-07 10:24 UTC, darius-m requested changes

2020-10-03 11:04 UTC, darius-m commented
Acum pare OK din punctul meu de vedere.

2020-10-03 11:04 UTC, darius-m approved these changes

2020-10-04 21:59 UTC, razvand approved these changes
All good. To merge.

2020-10-04 22:00 UTC, merged