Cristibm/lab 10 update
systems-cs-pub-ro/iocla pull request #117
Opened 2022-05-07 21:56 UTC by CristiBM

Replace the inline assembly tasks with 3 others that cover registers not being preserved by the callee and the mechanism of setting and restoring the state of the stack frame

2022-05-07 22:02 UTC, darius-m requested changes
The line indentations should be done using tabs, instead of spaces. You could use `sed` to update the lines with a rule like `s/^    /\t/`.

2022-05-07 22:22 UTC, darius-m requested changes
Mostly looks good. I've added some small styling suggestions. If you decide to accept them, please use the batch add option, otherwise each of them will generate a message for the PR.

Also, please address the coding style errors / warnings in the automatic checks (ignoring the licensing messages).

2022-05-07 22:22 UTC, darius-m commented on laborator/content/interactiune-c-assembly/README.md
> +Decomentați liniile marcate cu `TODO2` în fișierul assembly de la exercițiul anterior. Snippetul de cod realizează un apel al funcției `double_array()`, implementată în C, chiar înainte de afișarea v
```suggestion
Decomentați liniile marcate cu `TODO2` în fișierul assembly de la exercițiul anterior. Secvența de cod realizează un apel al funcției `double_array()`, implementată în C, chiar înainte de afișarea vectorului folosind funcția văzută anterior.
```

2022-05-07 22:22 UTC, darius-m commented on laborator/content/interactiune-c-assembly/README.md
> +Compilați și rulați programul. Pentru depanarea segfault-ului puteți folosi utilitarul `objdump` pentru a urmări codul assembly corespunzător funcției `double_array()`. Observați care din registrele
```suggestion
Compilați și rulați programul. Pentru depanarea segfault-ului puteți folosi utilitarul `objdump` pentru a urmări codul în limbaj de asamblare corespunzător funcției `double_array()`. Observați care din registrele folosite înainte și după apel sunt modificate de această funcție.
```

2022-05-07 22:22 UTC, darius-m commented on laborator/content/interactiune-c-assembly/6-7-regs-preserve/main.asm
> +
```suggestion
```

2022-05-07 22:22 UTC, darius-m commented on laborator/content/interactiune-c-assembly/6-7-regs-preserve/main.asm
> +    push newline
```suggestion
    add esp, 8
;   pop ecx
    loop next

    push newline
```

2022-05-07 22:22 UTC, darius-m commented on laborator/content/interactiune-c-assembly/3-stack-frame/print-hello.asm
> +# TODO: Adăugați instrucțiunea lipsă
```suggestion
;   TODO: Adăugați instrucțiunea lipsă
```

2022-05-07 22:22 UTC, darius-m commented on laborator/content/interactiune-c-assembly/6-7-regs-preserve/main.asm
> +; TODO1: Decomentați următoarele două linii comentate
```suggestion
;   TODO1: Decomentați următoarele două linii comentate
```

2022-05-07 22:22 UTC, darius-m commented on laborator/content/interactiune-c-assembly/6-7-regs-preserve/main.asm
> +; TODO2: Decomentați acest snippet de cod
```suggestion
;   TODO2: Decomentați acest snippet de cod
```

2022-05-08 18:32 UTC, CristiBM commented
> Mostly looks good. I've added some small styling suggestions. If you decide to accept them, please use the batch add option, otherwise each of them will generate a message for the PR.
> 
> Also, please address the coding style errors / warnings in the automatic checks (ignoring the licensing messages).

Solved the comments and coding style errors with the exception of the licensing messages and one regarding an allegedly 'misspelled' word in a code comment.

2022-05-08 19:27 UTC, darius-m approved these changes
Looks good now

2022-05-08 19:28 UTC, merged