docs: Add information about coding style
systems-cs-pub-ro/iocla pull request #138
Opened 2023-03-06 19:18 UTC by dumitrache-adrian92

Add a paragraph that explains what coding style should be used and how to use checkpatch.pl to find style errors.

This will make it easier for people to start contributing.

2023-03-07 05:30 UTC, teodutu requested changes

2023-03-07 05:30 UTC, teodutu commented on CONTRIBUTING.md
> +For code contributions, please respect the [Linux Kernel coding style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html). To make this process easier, download [checkpatch.pl](https://
Place each sentence in this paragraph on a separate line. This way it'll be easier to review. You should add [this paragraph](https://github.com/open-education-hub/operating-systems/blob/master/CONTRIBUTING.md#content-writing-style) to `CONTRIBUTING.md` as well.

2023-03-08 07:49 UTC, teodutu requested changes
The extra headings make the document easier to read and it looks less like a wall of text.

2023-03-08 07:49 UTC, teodutu commented on CONTRIBUTING.md
> +For code contributions, please respect the [Linux Kernel coding style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html).
```suggestion
## Coding Style

For code contributions, please respect the [Linux Kernel coding style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html).
```

2023-03-08 07:49 UTC, teodutu commented on CONTRIBUTING.md
> +For contributions to the documentation, write each sentence on a new line.
```suggestion
## Content Writing Style

For contributions to the documentation, write each sentence on a new line.
```

2023-03-08 08:20 UTC, dumitrache-adrian92 commented
Ok, my mistake. I wanted to make a separate pull request with the previous commit for a bunch of coding style changes. It went automatically here however. How do I go about fixing this?

2023-03-08 08:29 UTC, teodutu commented
> Ok, my mistake. I wanted to make a separate pull request with the previous commit for a bunch of coding style changes. It went automatically here however. How do I go about fixing this?

It would be easier if you had made this PR from a branch other than master. Now given the circumstances you should do the following:

```
$ git checkout -b fix-coding-style  # Create another branch from master. It will contain all these commits at first.

$ git reset HEAD~3 --hard  # Remove the last 3 commits (those in this PR) and their code changes.

$ cd /root/of/this/repo  # For the next command to work.

$ git checkout master -- laborator  # Get the changes to the laboratory/ folder from master on the new branch

$ git commit -sm 'your commit message'

$ git push -u origin fix-coding-style  # Push the "clean" coding style fixes onto another remote branch. Make a PR from this one.

$ git checkout master  # Start cleaning up the master branch.

$ git reset HEAD^ --hard  # Remove the last commit (the one with the code changes).

$ git push -f  # Remove it from the remote history as well.
```

2023-03-08 08:30 UTC, teodutu commented
You can use `git log` between either of the steps I suggested to check your current commits.

2023-03-08 08:53 UTC, dumitrache-adrian92 commented
That worked, thank you.

2023-03-08 08:56 UTC, teodutu approved these changes

2023-03-08 08:57 UTC, merged