lab/assembly-intro: Add CF vs OF example: Fixes #123
systems-cs-pub-ro/iocla pull request #139
Opened 2023-03-07 15:39 UTC by robertMihai19

Add CF and OF exercise

2023-03-07 15:47 UTC, dbaluta commented on laborator/content/introducere-asamblare/README.md
> +
There is something strange here. Commit subject says you add CF vs OF example, but here you also add another  Fibonacci exercise. 

This is confusing. A commit should only do one thing.

2023-03-08 02:50 UTC, teodutu requested changes
The code example is OK, but can be improved. See my inline suggestions, as well as the following:
- Don't make the setting of the 2 flags "cascade" from one another. Instead, create 3 independent snippets (in the same `.asm` file), one for each scenario. Use `test al, al` to clear both flags before each snippet
- The code you added looks more like the solution rather than the skeleton. The solution should be placed in `laborator/content/introducere-asamblare/solution/7-cf-of/`.
- Use 8-bit registers and values (`al` for example) so the numbers are easier to understand
- Mind the `checkpatch.pl` errors: remove the trailing whitespaces.

2023-03-08 02:50 UTC, teodutu commented on laborator/content/introducere-asamblare/7-cf-of/cf-of.asm
> +    PRINTF32 `CF si OF nu-s active\n\x0`
```suggestion
    PRINTF32 `CF si OF nu sunt active\n\x0`
```

2023-03-08 02:50 UTC, teodutu commented on laborator/content/introducere-asamblare/7-cf-of/cf-of.asm
> +    jmp no_flag
```suggestion
```
No need to `jmp` to a label just below the `jmp` instruction.

2023-03-08 02:50 UTC, teodutu commented on laborator/content/introducere-asamblare/README.md
> +Folosind operatia de add pe registrul `eax`, setati OF, apoi CF si apoi ambele flaguri simultan.
```suggestion
Folosind instrucțiunea `add` pe registrul `al`, setați OF, apoi CF și apoi ambele flaguri simultan.
```

2023-03-09 11:09 UTC, teodutu requested changes
It looks better now. Keep in mind to apply my inline comments from `cf.asm` to all code files.

2023-03-09 11:09 UTC, teodutu commented on laborator/content/introducere-asamblare/7-cf-of/cf.asm
> +    xor al, al
```suggestion
```
You reset `al` one line below.

2023-03-09 11:09 UTC, teodutu commented on laborator/content/introducere-asamblare/7-cf-of/cf.asm
> +    ;TODO: activati CF
```suggestion
    ;TODO: activati CF

```

2023-03-09 11:09 UTC, teodutu commented on laborator/content/introducere-asamblare/7-cf-of/cf.asm
> +no_flag1:
```suggestion
```
You never `jmp` to this label.

2023-03-09 11:09 UTC, teodutu commented on laborator/content/introducere-asamblare/7-cf-of/cf.asm
> +end1:
```suggestion
    jc carry_flag
    jmp end

carry_flag:
    PRINTF32 `CF activ\n\x0`

end:
```

2023-03-09 11:09 UTC, teodutu commented on laborator/content/introducere-asamblare/solution/7-cf-of/Makefile
> +BINARIES := cf-of cf of
Turn this into a link to `../../7-cf-of`.

2023-03-09 11:09 UTC, teodutu commented on laborator/content/introducere-asamblare/7-cf-of/Makefile
> +include ../../utils/Makefile.single
```suggestion
include ../../utils/Makefile.multiple
```

2023-03-09 11:10 UTC, teodutu commented
Also fix the `checkpatch.pl` errors. You have left some trailing whitespaces.

2023-03-14 05:04 UTC, teodutu requested changes
It's better now. I have made some additional suggestions. In addition to them, you need to remove the binaries (`cf`, `of` and `cf-of`) from `7-cf-of/` and then add them to a `.gitignore` file in the same directory so you don't add them again.

And don't mind the `checkpatch.pl` errors about whitespaces. I think Assembly confused the script somehow :)))

2023-03-14 05:04 UTC, teodutu commented on laborator/content/introducere-asamblare/solution/7-cf-of/Makefile
> +include ../../utils/Makefile.single
```suggestion
include ../../utils/Makefile.multiple
```

2023-03-14 05:04 UTC, teodutu commented on laborator/content/introducere-asamblare/solution/7-cf-of/cf-of.asm
> +no_flag:
```suggestion
```
Don't add labels that you don't use.

2023-03-14 05:04 UTC, teodutu commented on laborator/content/introducere-asamblare/solution/7-cf-of/cf.asm
> +no_flag1:
```suggestion
```

2023-03-14 05:04 UTC, teodutu commented on laborator/content/introducere-asamblare/solution/7-cf-of/cf.asm
> +end1:
```suggestion
    jc carry_flag
    jmp end

carry_flag:
    PRINTF32 `CF activ\n\x0`

end:
```
No need to add a `1` at the end.

2023-03-14 05:04 UTC, teodutu commented on laborator/content/introducere-asamblare/solution/7-cf-of/cf.asm
> +    add al, 1
This is the same example as `cf-of.asm`. Use something else, such as `200 + 100` to highlight the difference.

2023-03-16 03:01 UTC, teodutu requested changes
The code looks OK. Just eliminate the trailing whitespace highlighted by `checkpatch.pl`. This GitHub action runs whenever you make a new commit and leaves inline messages [1, 2]. Check them out after you make changes. No need to wait for me to make the same suggestions.

[1] https://github.com/systems-cs-pub-ro/iocla/pull/139/files
[2] https://github.com/systems-cs-pub-ro/iocla/actions/runs/4430626762/jobs/7772605275?pr=139

2023-03-17 03:20 UTC, teodutu approved these changes
Now it's good.

2023-03-17 03:21 UTC, merged