lab-03: Replace subtasks 3b-d
systems-cs-pub-ro/iocla pull request #146
Opened 2023-03-15 19:03 UTC by CristiBM

All tasks that required knowledge of assembly were replaced with an equivalent that only uses C.

2023-03-16 04:04 UTC, teodutu reviewed
I'm OK with the changes so far. Exercise 7 is nice. Another nice example would be to run `make` first without a Makefile, then with a makefile with another name and lastly using implicit Makefile rules.

2023-03-16 04:04 UTC, teodutu commented on laborator/content/etapele-compilarii/solution/01-one-diy/c-standalone/name.c
> +int puts(const char *);
```suggestion
int puts(const char *str);
```

2023-03-16 04:05 UTC, teodutu commented
@RazvanN7 please give your opinion as well.

2023-03-18 14:19 UTC, teodutu requested changes
I've just noticed that exercises `01-one-{tut,diy}/c-standalone` are still using Assembly files. You need to replace them with `.c` code as well, like you did with `03-entry-fix/b-no-main2/`.

2023-03-18 14:19 UTC, teodutu commented on laborator/content/etapele-compilarii/solution/01-one-diy/c-standalone/puts.asm
This file should go, together with its corresponding skeleton file.

2023-03-18 14:19 UTC, teodutu commented on laborator/content/etapele-compilarii/solution/01-one-diy/c-standalone/start.asm
Ditto: replace this with a `.c` file.

2023-03-18 14:19 UTC, teodutu commented on laborator/content/etapele-compilarii/solution/05-lib-fix/add.c
> +	return a+b;
```suggestion
	return a + b;
```
Same for the skelton.

2023-03-18 14:19 UTC, teodutu commented on laborator/content/etapele-compilarii/solution/05-lib-fix/sub.c
> +	return a-b;
```suggestion
	return a - b;
```
+ skeleton

2023-03-18 19:46 UTC, CristiBM commented
> I've just noticed that exercises `01-one-{tut,diy}/c-standalone` are still using Assembly files. You need to replace them with `.c` code as well, like you did with `03-entry-fix/b-no-main2/`.

This seems to be a bit problematic. The whole purpose of the sub-task is showing how you can link without libc and C runtime and I'm not sure how a _start() or puts() routine would be implemented in C without libc. For task 3 it was enough replacing _start() and I was able to keep libc linked; without it I couldn't have called exit() and it would have crashed.

2023-03-19 02:56 UTC, teodutu commented
> > I've just noticed that exercises `01-one-{tut,diy}/c-standalone` are still using Assembly files. You need to replace them with `.c` code as well, like you did with `03-entry-fix/b-no-main2/`.
> 
> This seems to be a bit problematic. The whole purpose of the sub-task is showing how you can link without libc and C runtime and I'm not sure how a _start() or puts() routine would be implemented in C without libc. For task 3 it was enough replacing _start() and I was able to keep libc linked; without it I couldn't have called exit() and it would have crashed.

Yeah, you're right. Then I don't see any solution other than removing this exercise altogether :man_shrugging:.

2023-03-19 09:52 UTC, CristiBM commented
> > > I've just noticed that exercises `01-one-{tut,diy}/c-standalone` are still using Assembly files. You need to replace them with `.c` code as well, like you did with `03-entry-fix/b-no-main2/`.
> > 
> > 
> > This seems to be a bit problematic. The whole purpose of the sub-task is showing how you can link without libc and C runtime and I'm not sure how a _start() or puts() routine would be implemented in C without libc. For task 3 it was enough replacing _start() and I was able to keep libc linked; without it I couldn't have called exit() and it would have crashed.
> 
> Yeah, you're right. Then I don't see any solution other than removing this exercise altogether man_shrugging.

I removed subtask 1-c.
Honestly, I would have voted for leaving it in, with the risk of introducing a bit of confusion, but if the general opinion is that it's not worth it, I'm ok with that :))

2023-03-19 12:25 UTC, teodutu approved these changes
I think it's OK now. We can revive task 1-c next semester if it turns out that removing it was exaggerated. For now, let's play it safe.

2023-03-19 12:29 UTC, teodutu commented
Now squash these commits into a single one formatted like this: `lab/compile: Replace Assembly exercises and add solutions` so it's easier to merge.

2023-03-20 05:19 UTC, merged