lab/toolchain-decompilare: Added solutions, Modified README
systems-cs-pub-ro/iocla pull request #153
Opened 2023-03-25 08:43 UTC by RaresCon

2023-03-25 09:17 UTC, teodutu requested changes
You forgot to add the solutions and removed some exercises that you shouldn't have.

2023-03-25 09:17 UTC, teodutu commented on laborator/content/toolchain-decompilare/2-warm-up-gotos/Makefile
Why did you remove these files?

2023-03-25 09:17 UTC, teodutu commented on laborator/content/toolchain-decompilare/README.md
> +În alte cuvinte, tot codul trebuie să fie scris în interiorul funcției main, iar modificarea fluxului de control (saltul la altă zonă de cod) se face doar prin intermediul secvențelor de tipul if (co
```suggestion
În alte cuvinte, tot codul trebuie să fie scris în interiorul funcției main, iar modificarea fluxului de control (saltul la altă zonă de cod) se face doar prin intermediul secvențelor de tipul `if (conditie) goto eticheta;` sau `goto eticheta;`.
```
Use backquotes for (pseudo-)code snippets.

2023-03-25 09:17 UTC, teodutu commented on laborator/content/toolchain-decompilare/README.md
> +**2.2** În mod asemănător modificați instrucțiunea **continue** din `ignore_the_comments.c`, aflat în directorul `b-ignore_the_comments`, astfel încât funcționalitatea codului să se păstreze.
```suggestion
**2.2** În mod asemănător modificați instrucțiunea `continue` din `ignore_the_comments.c`, aflat în directorul `b-ignore_the_comments`, astfel încât funcționalitatea codului să se păstreze.
```

2023-03-25 09:17 UTC, teodutu commented on laborator/content/toolchain-decompilare/README.md
> +**2.1** Modificați codul sursă din fișierul `bogosort.c`, aflat în directorul `a-bogosort`, ([Bogosort](https://en.wikipedia.org/wiki/Bogosort)) prin înlocuirea instrucțiunii **break** cu o instrucți
```suggestion
**2.1** Modificați codul sursă din fișierul `bogosort.c`, aflat în directorul `a-bogosort`, ([Bogosort](https://en.wikipedia.org/wiki/Bogosort)) prin înlocuirea instrucțiunii `break` cu o instrucțiune `goto` astfel încât funcționalitatea să se păstreze.
```

2023-03-25 10:03 UTC, RaresCon commented
> You forgot to add the solutions and removed some exercises that you shouldn't have.

Don't really know what happened there, as I've made sure to add all changes. I revised the last commit to include the files.

2023-03-26 06:58 UTC, teodutu requested changes
I like your changes to exercises 2 and 3. In addition to my comments, mind the `checkpatch.pl` errors: https://github.com/systems-cs-pub-ro/iocla/actions/runs/4518662503/jobs/7958678153?pr=153.

2023-03-26 09:05 UTC, RaresCon commented on laborator/content/toolchain-decompilare/solution/5-old-hits/README
> +Exercițiul necesită găsirea unei valori generate random în main folosind gdb
Should I add that title to the README?

2023-03-26 10:34 UTC, RaresCon commented
> I like your changes to exercises 2 and 3. In addition to my comments, mind the `checkpatch.pl` errors: https://github.com/systems-cs-pub-ro/iocla/actions/runs/4518662503/jobs/7958678153?pr=153.

I get this error when running `checkpatch.pl` on `old-hits.c`: `Error: WARNING: break quoted strings at a space character`. It is coming from the next declaration:

`char links[] =
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ"
		"https://www.youtube.com/watch?v=3rzgrP7VA_Q"
		"https://www.youtube.com/watch?v=ZZ5LpwO-An4"
		"https://www.youtube.com/watch?v=y6120QOlsfU"
		"https://www.youtube.com/watch?v=0q6yphdZhUA"
		"https://www.youtube.com/watch?v=989-7xsRLR4"
		"https://www.youtube.com/watch?v=7yh9i0PAjck"
		"https://www.youtube.com/watch?v=04F4xlWSFh0"
		"https://www.youtube.com/watch?v=hAAlDoAtV7Y"
		"https://www.youtube.com/watch?v=NAEppFUWLfc";`

Any idea how to rezolve this?

2023-03-27 02:58 UTC, teodutu commented on laborator/content/toolchain-decompilare/solution/5-old-hits/README
> +Exercițiul necesită găsirea unei valori generate random în main folosind gdb
Yes. It's in my suggestion: `# Writeup`.

2023-03-27 03:03 UTC, teodutu commented
> > I like your changes to exercises 2 and 3. In addition to my comments, mind the `checkpatch.pl` errors: https://github.com/systems-cs-pub-ro/iocla/actions/runs/4518662503/jobs/7958678153?pr=153.
> 
> I get this error when running `checkpatch.pl` on `old-hits.c`: `Error: WARNING: break quoted strings at a space character`. It is coming from the next declaration:
> 
> `char links[] = "https://www.youtube.com/watch?v=dQw4w9WgXcQ" "https://www.youtube.com/watch?v=3rzgrP7VA_Q" "https://www.youtube.com/watch?v=ZZ5LpwO-An4" "https://www.youtube.com/watch?v=y6120QOlsfU" "https://www.youtube.com/watch?v=0q6yphdZhUA" "https://www.youtube.com/watch?v=989-7xsRLR4" "https://www.youtube.com/watch?v=7yh9i0PAjck" "https://www.youtube.com/watch?v=04F4xlWSFh0" "https://www.youtube.com/watch?v=hAAlDoAtV7Y" "https://www.youtube.com/watch?v=NAEppFUWLfc";`
> 
> Any idea how to rezolve this?

The implementation of `old-hits.c` is kind of messy because it considers all links are one contiguous string. To fix this, change the `links` array to a array of strings and copy them to a contiguous buffer which you'll then encrypt instead of `links`.

2023-03-27 10:36 UTC, RaresCon commented
I've fixed the errors given by `checkpatch.pl`, but I see that it still tracks old errors, that are not present in the current commit.

2023-03-27 10:40 UTC, teodutu commented
> I've fixed the errors given by `checkpatch.pl`, but I see that it still tracks old errors, that are not present in the current commit.

This is because `checkpatch.pl` verifies all commits in a PR. If you want to silence previous errors, you have to squash your broken commits into a single, correct one.

2023-03-27 10:44 UTC, teodutu requested changes
Just make a slight improvement to `old-hits.c` and then it'll be fine.

2023-03-28 04:17 UTC, teodutu approved these changes
:ok_hand:

2023-03-28 04:17 UTC, merged