2020 laborator 10 markdown
systems-cs-pub-ro/iocla pull request #19
Opened 2021-08-31 10:22 UTC by samoilescusebastian

2021-09-01 22:01 UTC, darius-m requested changes
Arată bine în mare parte, dar trebuie aduse niște modificări pentru consistență cu celelalte readme-uri.

2021-09-02 17:35 UTC, samoilescusebastian commented on laborator/lab-10/README.md
> +  - asamblorul ```nasm```
Done

2021-09-02 17:35 UTC, samoilescusebastian commented on laborator/lab-10/README.md
> +> În cadrul laboratoarelor vom folosi repository-ul de git al materiei IOCLA - https://github.com/systems-cs-pub-ro/iocla.
Done

2021-09-03 06:56 UTC, darius-m reviewed
Acum arată mai bine acum.

Mesajele se pot corecta într-un pull local folosind `git rebase -i @~10` (exemplu pentru un rebase interactiv a ultimelor 10 commit-uri), schimbat `pick` în `rebase`/`r` pentru commit-urile care trebuie corectate, schimbat textul, iar apoi `git push -f origin 2020-laborator-10-markdown`. Este nevoie de force la push pentru că se modifică istoricul din github, dar ar trebui să fie actualizat automat PR-ul. Commit-urile pot să rămână ca acum, dar ar fi bine să fie respectat formatul în viitor.

2021-09-03 06:56 UTC, darius-m commented on laborator/lab-10/README.md
> +> ```Assembly
Aici ar trebui să fie `Bash` în loc de `Assembly` (se vede syntax highlight-ul greșit în readme).

2021-09-03 11:22 UTC, samoilescusebastian commented on laborator/lab-10/README.md
> +> ```Assembly
Done

2021-09-03 11:22 UTC, samoilescusebastian commented
> Acum arată mai bine acum, dar te rog să respecți formatul cu `Lab10: ...` pentru commit-uri.
> 
> Mesajele se pot corecta într-un pull local folosind `git rebase -i @~10` (exemplu pentru un rebase interactiv a ultimelor 10 commit-uri), schimbat `pick` în `rebase`/`r` pentru commit-urile care trebuie corectate, schimbat textul, iar apoi `git push -f origin 2020-laborator-10-markdown`. Este nevoie de force la push pentru că se modifică istoricul din github, dar ar trebui să fie actualizat automat PR-ul. Commit-urile pot să rămână ca acum, dar ar fi bine să fie respectat formatul în viitor.

2021-09-04 15:45 UTC, darius-m approved these changes
Mi se pare OK. Nu am verificat erori gramaticale, dar ca format este bine

2021-09-06 14:08 UTC, merged