Added README.md for lab 7 2020
systems-cs-pub-ro/iocla pull request #20
Opened 2021-08-31 12:55 UTC by Robert-ML

2021-09-01 21:45 UTC, darius-m requested changes
Arată OK în mare parte, cu excepția break-urilor.

2021-09-01 21:45 UTC, darius-m commented on laborator/lab-07/README.md
> +<br></br>
Vezi fișierul parsat. Break-urile lasă prea mult spațiu în text în general și trebuie scoase.

2021-09-02 12:44 UTC, dbaluta commented
For next PRs, please try to follow these rules:

https://chris.beams.io/posts/git-commit/#seven-rules

2021-09-02 12:51 UTC, darius-m commented
> For next PRs, please try to follow these rules:
> 
> https://chris.beams.io/posts/git-commit/#seven-rules

Since this is a separate branch, you can rebase interactively (using `git rebase -i @~10`), change `pick` to `reword` / `r` for each commit and change the text (e.g., `Lab07: Add README.md`). Then, do a forced push using `git push -f master 2020-laborator-7-markdown`. The changes will be automatically picked up by the PR.

2021-09-06 14:20 UTC, merged