Adaugare laborator 4 2020 markdown
systems-cs-pub-ro/iocla pull request #21
Opened 2021-08-31 14:12 UTC by Teo48

2021-09-01 21:48 UTC, darius-m reviewed
Arată ok.

2021-09-01 21:48 UTC, darius-m commented on laborator/lab-04/README.md
> +>```
Probabil ar merge pus tipul de sintaxă și aici.

2021-09-05 10:08 UTC, darius-m requested changes

2021-09-05 10:08 UTC, darius-m commented on laborator/lab-04/README.md
> +>**NOTE**: În cadrul laboratoarelor vom folosi repository-ul de git al materiei IOCLA - (https://github.com/systems-cs-pub-ro/iocla). Repository-ul este clonat pe desktop-ul mașinii virtuale. Pentru
Linkul de la `git clone` nu ar trebui să fie înconjurat de paranteze.

2021-09-05 14:43 UTC, Teo48 commented on laborator/lab-04/README.md
> +>```
Intr-adevar, pentru consistenta e mai ok. Am modificat.

2021-09-05 14:43 UTC, Teo48 commented on laborator/lab-04/README.md
> +>**NOTE**: În cadrul laboratoarelor vom folosi repository-ul de git al materiei IOCLA - (https://github.com/systems-cs-pub-ro/iocla). Repository-ul este clonat pe desktop-ul mașinii virtuale. Pentru
Done.

2021-09-05 15:35 UTC, darius-m reviewed
Arată OK, dar pe viitor te rog să păstrezi formatul cu `Lab04: ...` în titlul commit-urilor. Altfel o să apară multe commit-uri în istoric cu text similar.

Dacă vrei să corectezi, poți folosi `git commit --amend` (pentru a corecta doar ultimul commit), sau `git rebase -i @~10` (pentru a vedea o listă cu ultimele 10 commit-uri), schimbi `pick` în `reword` / `r` și apoi corectezi textul din commit. După ce corectezi, este nevoie de `git push -f origin 2020-laborator-4-markdown` (este nevoie de force pentru că se modifică istoricul). De data asta este OK să rămână și așa.

2021-09-05 15:35 UTC, darius-m approved these changes

2021-09-06 14:20 UTC, merged