Add demos for lab08.
systems-cs-pub-ro/iocla pull request #70
Opened 2021-12-24 15:52 UTC by gabrielmocanu

Add demos for lab08.

Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>

2022-01-05 16:44 UTC, gabrielmocanu commented
@cristian-vijelie  Can you take a look on this, please?

2022-01-10 09:25 UTC, cristian-vijelie requested changes
I think that the Makefile should also build the 2nd demo, too.

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/Makefile
> +LDFLAGS = -m32 -g
```suggestion
LDFLAGS = -m32 -g -no-pie
```

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing-2.asm
> +%define NUM 5
```suggestion
```

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing-2.asm
> +%define NUM 5
It's not used, remove it

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing-2.asm
> +global main
```suggestion
section .text
    extern printf
    global main

; esp -> stack pointer
; ebp -> base pointer
```

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing-2.asm
> +
```suggestion
```

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing-2.asm
> +
```suggestion
```

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing.asm
> +%define NUM 5
```suggestion
```

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing.asm
> +%define NUM 5
Not used, remove it

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing.asm
> +main:
```suggestion
section .text
    extern printf
    global main

main:
```

2022-01-10 09:25 UTC, cristian-vijelie commented on laborator/content/stiva/demo/stack-addressing/stack-addressing.asm
> +
```suggestion
```

2022-03-29 09:12 UTC, RazvanN7 commented
@gabrielmocanu Please address the review and let's get this in.

2022-06-20 07:13 UTC, cristian-vijelie commented on laborator/content/stiva/demo/sum_n_interm/sum_n_interm.asm
> +    add [sum], eax
E intentionata diferenta de aici de coding-style? <instr><spatiu><argumente> vs <instr><tab><argumente>

2022-06-20 07:14 UTC, cristian-vijelie requested changes
Mai sunt cateva schimbari necesare. Am adaugat 2 comment-uri, care se aplica in mai multe locuri

2024-03-30 15:14 UTC, merged